# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hp.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        MainWindow.setStyleSheet("background-color: None;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #312e2d;")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 240, 291, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Pictures/assets.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 240, 291, 291))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Pictures/liabilities.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1040, 240, 291, 291))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Pictures/reports.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 240, 291, 291))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Pictures/redaction.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 540, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #f1dbce;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 540, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #f1dbce;")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 250, 281, 271))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: 3px;\n"
"border-radius:40;\n"
"}\n"
"QPushButton:hover {\n"
"background: rgba(83, 80, 79, 0.4);\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 250, 281, 271))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: 3px;\n"
"border-radius:40;\n"
"}\n"
"QPushButton:hover {\n"
"background: rgba(83, 80, 79, 0.4);\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 250, 281, 271))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: 3px;\n"
"border-radius:40;\n"
"}\n"
"QPushButton:hover {\n"
"background: rgba(83, 80, 79, 0.4);\n"
"}\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1040, 250, 281, 271))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: 3px;\n"
"border-radius:40;\n"
"}\n"
"QPushButton:hover {\n"
"background: rgba(83, 80, 79, 0.4);\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1110, 540, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #f1dbce;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(750, 540, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #f1dbce;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 100, 401, 91))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("color: #f1dbce;")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Liabilities"))
        self.label_6.setText(_translate("MainWindow", "Assets"))
        self.label_7.setText(_translate("MainWindow", "Reports"))
        self.label_8.setText(_translate("MainWindow", "Redaction"))
        self.label_9.setText(_translate("MainWindow", "Home Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
